# Generated by Django 4.2 on 2023-05-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='briefing',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='imagem',
            field=models.TextField(),
        ),
    ]
