# Generated by Django 4.2 on 2023-05-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_perfume_briefing_alter_perfume_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='briefing',
            field=models.CharField(max_length=50),
        ),
    ]
