# Generated by Django 4.2 on 2023-05-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_perfume_briefing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='briefing',
            field=models.CharField(max_length=100),
        ),
    ]
