# Generated by Django 4.2 on 2023-05-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_notas_perfume_briefing_alter_perfume_imagem_and_more'),
        ('home', '0004_alter_perfume_briefing'),
    ]

    operations = [
    ]
