# Generated by Django 4.2 on 2023-05-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_notas_options_perfume_notas_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='notas_base',
            field=models.ManyToManyField(blank=True, related_name='Notas_de_base', to='home.notas'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='notas_corpo',
            field=models.ManyToManyField(blank=True, related_name='Notas_de_corpo', to='home.notas'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='notas_saida',
            field=models.ManyToManyField(blank=True, related_name='Notas_de_saida', to='home.notas'),
        ),
    ]
