# Generated by Django 4.2 on 2023-05-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_perfume_notas_base_alter_perfume_notas_corpo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notas',
            new_name='Nota',
        ),
    ]
