version: "3.8"

services:
  perfumes:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - gm

  db:
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
    ports:
      - "5432:5432"
    volumes: 
      - ./data:/var/lib/postgresql/data
    networks:
      - gm

networks:
  gm:
